version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:8000"
    volumes:
      - ./app/nginx_conf:/etc/nginx/conf.d
      - ./data/letsencrypt:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web

  web:
    build: ./
    hostname: web
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/tick.log:/app/tick.log
    env_file:
      - "envfile"
