version: '3'
services:
  paul_web:
    container_name: paul_web
    build: ./
    hostname: web
    ports:
      - "8001:8001"
    volumes:
      - /home/ubuntu/tick.log:/app/tick.log
    environment:
      VIRTUAL_HOST: paulwallington.co.za
      VIRTUAL_PORT: 8001
      LETSENCRYPT_HOST: paulwallington.co.za
      LETSENCRYPT_EMAIL: lukekingsleybell@mail.com
    env_file:
      - "envfile"
networks:
  default:
    external:
      name: nginx-proxy
